export interface BookMetadata {
  amazonMarketplace: string;
  category: string;
  targetMarket: string;
  topic: string;
  author: string;
  title: string;
  subtitle: string;
  description: string;
}

export interface ReferenceBook {
  title: string;
  author: string;
  visualHook: string; // Description of why this cover works
}

export interface GroundingData {
  trends: string;
  references: ReferenceBook[];
  sources: { uri: string; title: string }[];
}

export enum AppStep {
  DETAILS = 'DETAILS',
  RESEARCH = 'RESEARCH',
  GENERATION = 'GENERATION',
  EDITING = 'EDITING',
  VIDEO = 'VIDEO'
}

export const CATEGORIES = [
  "Mystery, Thriller & Suspense",
  "Romance",
  "Science Fiction & Fantasy",
  "Self-Help",
  "Business & Money",
  "Cookbooks, Food & Wine",
  "Biographies & Memoirs",
  "History",
  "Children's Books",
  "Health, Fitness & Dieting"
];

export const MARKETPLACES = [
  { id: 'it', label: 'Italia (Amazon.it)', name: 'Amazon.it' },
  { id: 'us', label: 'USA (Amazon.com)', name: 'Amazon.com' },
  { id: 'uk', label: 'Regno Unito (Amazon.co.uk)', name: 'Amazon.co.uk' },
  { id: 'de', label: 'Germania (Amazon.de)', name: 'Amazon.de' },
];

export type Language = 'en' | 'it' | 'fr' | 'de' | 'es';

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'it', label: 'Italiano' },
  { code: 'fr', label: 'Français' },
  { code: 'de', label: 'Deutsch' },
  { code: 'es', label: 'Español' },
];

export const TRANSLATIONS = {
  en: {
    appTitle: "KDP Master",
    subtitle: "Powered by Gemini 3 & Veo",
    conceptSetup: "Concept Setup",
    marketplaceLabel: "Target National Market",
    amazonCategory: "Amazon Category",
    targetMarketLabel: "Market Niche (Specific)",
    authorName: "Author Name",
    bookTopic: "Book Topic / Premise",
    generateBtn: "Generate Best Seller",
    refineExport: "Refine & Export",
    metadataEditable: "Metadata (Editable)",
    aiImageEdit: "AI Image Edit (Nano Banana)",
    veoTrailer: "Veo Cinematic Trailer",
    veoNote: "Requires a paid Google Cloud Project key selection.",
    startOver: "Start Over",
    marketResearch: "Market Research",
    inspirationBoard: "Inspiration Moodboard",
    viewCover: "View Cover",
    shareDesign: "Share Design",
    downloadCover: "Download Cover",
    designing: "Designing...",
    noCover: "No cover generated yet",
    analyzing: "Analyzing Best Sellers on",
    crafting: "Crafting killer title and copy...",
    painting: "Painting 3 masterpieces (this may take a moment)...",
    applyingEdits: "Applying edits with Nano Banana (Gemini 2.5 Flash Image)...",
    generatingVideo: "Generating Veo cinematic trailer (this takes a minute)...",
    errorKey: "Something went wrong. Please check your API key and try again.",
    errorEdit: "Edit failed.",
    errorVideo: "Video generation failed. Ensure you have a paid project selected.",
    placeholderAuthor: "e.g. J.K. Rowling",
    placeholderTopic: "e.g. A detective discovers a time machine in Victorian London...",
    placeholderMarket: "e.g. Cozy Mystery for Cat Lovers, Keto for Women over 50...",
    placeholderEdit: "e.g. Add a red moon, make it darker...",
    placeholderVideo: "e.g. Pan down slowly, embers flying...",
    veoGenerated: "Veo Generated",
    editBtn: "Edit",
    animateBtn: "Animate",
    variations: "Select Your Cover",
    option: "Option",
    downloadBtn: "Download"
  },
  it: {
    appTitle: "KDP Master",
    subtitle: "Basato su Gemini 3 & Veo",
    conceptSetup: "Impostazione Concetto",
    marketplaceLabel: "Mercato Nazionale di Destinazione",
    amazonCategory: "Categoria Amazon",
    targetMarketLabel: "Nicchia di Mercato (Specifico)",
    authorName: "Nome Autore",
    bookTopic: "Argomento / Premessa del Libro",
    generateBtn: "Genera Best Seller",
    refineExport: "Rifinisci & Esporta",
    metadataEditable: "Metadati (Modificabili)",
    aiImageEdit: "Modifica Immagine AI (Nano Banana)",
    veoTrailer: "Trailer Cinematico Veo",
    veoNote: "Richiede la selezione di una chiave Google Cloud Project a pagamento.",
    startOver: "Ricomincia",
    marketResearch: "Ricerche di Mercato",
    inspirationBoard: "Moodboard Ispirazionale",
    viewCover: "Vedi Copertina",
    shareDesign: "Condividi Design",
    downloadCover: "Scarica",
    designing: "Progettazione in corso...",
    noCover: "Nessuna copertina generata",
    analyzing: "Analisi dei Best Seller su",
    crafting: "Creazione di titolo e testo accattivanti...",
    painting: "Dipingendo 3 capolavori (potrebbe richiedere un momento)...",
    applyingEdits: "Applicazione modifiche con Nano Banana...",
    generatingVideo: "Generazione trailer Veo (richiede un minuto)...",
    errorKey: "Qualcosa è andato storto. Controlla la tua chiave API e riprova.",
    errorEdit: "Modifica fallita.",
    errorVideo: "Generazione video fallita. Assicurati di aver selezionato un progetto a pagamento.",
    placeholderAuthor: "es. J.K. Rowling",
    placeholderTopic: "es. Un detective scopre una macchina del tempo...",
    placeholderMarket: "es. Gialli per amanti dei gatti, Dieta Keto per over 50...",
    placeholderEdit: "es. Aggiungi una luna rossa, rendilo più scuro...",
    placeholderVideo: "es. Panoramica lenta verso il basso, braci volanti...",
    veoGenerated: "Generato con Veo",
    editBtn: "Modifica",
    animateBtn: "Anima",
    variations: "Scegli la tua Copertina",
    option: "Opzione",
    downloadBtn: "Scarica"
  },
  fr: {
    appTitle: "KDP Master",
    subtitle: "Propulsé par Gemini 3 & Veo",
    conceptSetup: "Configuration du Concept",
    marketplaceLabel: "Marché National Cible",
    amazonCategory: "Catégorie Amazon",
    targetMarketLabel: "Niche de Marché (Spécifique)",
    authorName: "Nom de l'Auteur",
    bookTopic: "Sujet / Prémisse du Livre",
    generateBtn: "Générer un Best-Seller",
    refineExport: "Affiner & Exporter",
    metadataEditable: "Métadonnées (Modifiables)",
    aiImageEdit: "Édition d'Image AI (Nano Banana)",
    veoTrailer: "Bande-annonce Cinématique Veo",
    veoNote: "Nécessite la sélection d'une clé de projet Google Cloud payante.",
    startOver: "Recommencer",
    marketResearch: "Étude de Marché",
    inspirationBoard: "Tableau d'Inspiration",
    viewCover: "Voir la Couverture",
    shareDesign: "Partager le Design",
    downloadCover: "Télécharger",
    designing: "Conception en cours...",
    noCover: "Aucune couverture générée",
    analyzing: "Analyse des Best-Sellers sur",
    crafting: "Création d'un titre et d'un texte accrocheurs...",
    painting: "Peinture de 3 chefs-d'œuvre (cela peut prendre un moment)...",
    applyingEdits: "Application des modifications avec Nano Banana...",
    generatingVideo: "Génération de la bande-annonce Veo (cela prend une minute)...",
    errorKey: "Une erreur s'est produite. Veuillez vérifier votre clé API.",
    errorEdit: "L'édition a échoué.",
    errorVideo: "La génération de la vidéo a échoué. Projet payant requis.",
    placeholderAuthor: "ex. J.K. Rowling",
    placeholderTopic: "ex. Un détective découvre une machine à voyager dans le temps...",
    placeholderMarket: "ex. Mystère douillet pour amoureux des chats...",
    placeholderEdit: "ex. Ajoutez une lune rouge, rendez-le plus sombre...",
    placeholderVideo: "ex. Panoramique lent vers le bas, braises volantes...",
    veoGenerated: "Généré par Veo",
    editBtn: "Éditer",
    animateBtn: "Animer",
    variations: "Choisissez votre couverture",
    option: "Opzione",
    downloadBtn: "Télécharger"
  },
  de: {
    appTitle: "KDP Master",
    subtitle: "Unterstützt von Gemini 3 & Veo",
    conceptSetup: "Konzept-Setup",
    marketplaceLabel: "Nationaler Zielmarkt",
    amazonCategory: "Amazon Kategorie",
    targetMarketLabel: "Marktnische (Spezifisch)",
    authorName: "Autorenname",
    bookTopic: "Buchthema / Prämisse",
    generateBtn: "Bestseller Generieren",
    refineExport: "Verfeinern & Exportieren",
    metadataEditable: "Metadaten (Bearbeitbar)",
    aiImageEdit: "KI Bildbearbeitung (Nano Banana)",
    veoTrailer: "Veo Kino-Trailer",
    veoNote: "Erfordert die Auswahl eines kostenpflichtigen Google Cloud Project-Schlüssels.",
    startOver: "Neu Beginnen",
    marketResearch: "Marktforschung",
    inspirationBoard: "Inspirations-Moodboard",
    viewCover: "Cover Ansehen",
    shareDesign: "Design Teilen",
    downloadCover: "Herunterladen",
    designing: "Designen...",
    noCover: "Kein Cover generiert",
    analyzing: "Analysiere Bestseller auf",
    crafting: "Erstelle fesselnden Titel und Text...",
    painting: "Male 3 Meisterwerke (dies kann einen Moment dauern)...",
    applyingEdits: "Wende Änderungen mit Nano Banana an...",
    generatingVideo: "Generiere Veo-Trailer (dauert eine Minute)...",
    errorKey: "Etwas ist schief gelaufen. Bitte überprüfe deinen API-Schlüssel.",
    errorEdit: "Bearbeitung fehlgeschlagen.",
    errorVideo: "Videogenerierung fehlgeschlagen. Kostenpflichtiges Projekt erforderlich.",
    placeholderAuthor: "z.B. J.K. Rowling",
    placeholderTopic: "z.B. Ein Detektiv entdeckt eine Zeitmaschine...",
    placeholderMarket: "z.B. Cosy Crime für Katzenliebhaber...",
    placeholderEdit: "z.B. Füge einen roten Mond hinzu...",
    placeholderVideo: "z.B. Langsamer Schwenk nach unten...",
    veoGenerated: "Veo Generiert",
    editBtn: "Bearbeiten",
    animateBtn: "Animieren",
    variations: "Wähle dein Cover",
    option: "Opzione",
    downloadBtn: "Herunterladen"
  },
  es: {
    appTitle: "KDP Master",
    subtitle: "Impulsado por Gemini 3 y Veo",
    conceptSetup: "Configuración del Concepto",
    marketplaceLabel: "Mercado Nacional Objetivo",
    amazonCategory: "Categoría de Amazon",
    targetMarketLabel: "Nicho de Mercado",
    authorName: "Nombre del Autor",
    bookTopic: "Tema del Libro / Premisa",
    generateBtn: "Generar Best Seller",
    refineExport: "Refinar y Exportar",
    metadataEditable: "Metadatos (Editables)",
    aiImageEdit: "Edición de Imagen IA (Nano Banana)",
    veoTrailer: "Tráiler Cinematográfico Veo",
    veoNote: "Requiere la selección de una clave de proyecto de Google Cloud de pago.",
    startOver: "Empezar de Nuevo",
    marketResearch: "Investigación de Mercado",
    inspirationBoard: "Tablero de Inspiración",
    viewCover: "Ver Portada",
    shareDesign: "Compartir Diseño",
    downloadCover: "Descargar",
    designing: "Diseñando...",
    noCover: "Aún no se ha generado ninguna portada",
    analyzing: "Analizando los Best Sellers de",
    crafting: "Creando título y texto atractivos...",
    painting: "Pintando 3 obras maestras (esto puede tomar un momento)...",
    applyingEdits: "Aplicando ediciones con Nano Banana...",
    generatingVideo: "Generando tráiler Veo (esto toma un minuto)...",
    errorKey: "Algo salió mal. Por favor verifica tu clave API.",
    errorEdit: "La edición falló.",
    errorVideo: "La generación de video falló. Se requiere proyecto de pago.",
    placeholderAuthor: "ej. J.K. Rowling",
    placeholderTopic: "ej. Un detective descubre una máquina del tiempo...",
    placeholderMarket: "ej. Misterio acogedor para amantes de los gatos...",
    placeholderEdit: "ej. Añade una luna roja, hazlo más oscuro...",
    placeholderVideo: "ej. Panorámica lenta hacia abajo...",
    veoGenerated: "Generado por Veo",
    editBtn: "Editar",
    animateBtn: "Animar",
    variations: "Elige tu Portada",
    option: "Opción",
    downloadBtn: "Descargar"
  }
};